[package]
name = "pupper-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eframe = "0.27"
egui_extras = { version = "0.27", features = ["image", "all_loaders", "svg"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
