build: 
    cargo build
    cargo zigbuild --target aarch64-unknown-linux-gnu --release

sync: build
    rsync -hazvP target/aarch64-unknown-linux-gnu/ pi@pupper.local:/home/pi/pupperv3-monorepo/pupper-rs/target/

run-ssh:
    DISPLAY=:0 ./target/release/pupper-rs