build: 
    cargo build
    cargo zigbuild --target aarch64-unknown-linux-gnu

sync: build
    rsync -hazvP target/aarch64-unknown-linux-gnu/debug/ pi@pupper.local:/home/pi/pupper-rs/

run-ssh:
    DISPLAY=:0 cargo run