controller_manager:
  ros__parameters:
    update_rate: 260 # Hz

    # Single animation controller that handles all animations
    animation_controller:
      type: animation_controller/AnimationController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

# Animation controller - handles all animations (auto-discovers CSV files)
animation_controller:
  ros__parameters:
    update_rate: 260 # Hz
    default_animation: "twerk_recording_2025-09-04_16-14-51_0"

joint_state_broadcaster:
  ros__parameters:
    update_rate: 260
    use_local_topics: false

imu_sensor_broadcaster:
  ros__parameters:
    update_rate: 260
    frame_id: base_link
    sensor_name: imu_sensor
